export const signinType = "SIGNINTYPE";
export const signoutType = "SIGNOUTTYPE";
export const showSpinner= "SHOWSPINNER";
export const hideSpinner= "HIDESPINNER";
export const errorLogin= "ERRORLOGIN";
export const fetchDashboard= "FETCHDASHBOARD"
export const fetchErranderRequested= "FETCHERRANDERREQUESTED"
export const fetchErranderVerified= "FETCHERRANDERVERIFIED"
export const fetchErranderDeclined= "FETCHERRANDERDECLINED"
export const fetchCustomerData= "FETCHCUSTOMERDATA"
export const selectedErrander= "SELECTEDERRANDER"
export const selectedCustomer= "SELECTEDCUSTOMER"
export const fetchTodayOrder= "FETCHTODAYORDER"
export const fetchThisWeekOrder= "FETCHTHISWEEKORDER"
export const fetchDateOrder= "FETCHDATEORDER"
export const updateAuth= "UPDATEAUTH";
export const setSelectedDate="SETSELECTEDDATE"
export const fetchBlogger="FETCHBLOGGER"